- name: Install Docker dependencies
  apt:
    name:
      - apt-transport-https
      - ca-certificates
      - curl
      - gnupg
      - lsb-release
    update_cache: yes
    state: present

- name: Download Docker GPG key
  get_url:
    url: https://download.docker.com/linux/ubuntu/gpg
    dest: /etc/apt/trusted.gpg.d/docker.gpg
    mode: '0644'


- name: Add Docker repo
  apt_repository:
    repo: deb [arch=amd64] https://download.docker.com/linux/ubuntu focal stable
    state: present
    update_cache: yes

- name: Install Docker CE
  apt:
    name:
      - docker-ce
      - docker-ce-cli
      - containerd.io
    state: present
    update_cache: yes

- name: Enable and start Docker
  systemd:
    name: docker
    enabled: true
    state: started

- name: Add Jenkins and current user to docker group
  user:
    name: "{{ item }}"
    groups: docker
    append: yes
  loop:
    - jenkins
    - "{{ lookup('env', 'USER') }}"

