- name: Ensure app directory exists
  file:
    path: /opt/myapp
    state: directory
    mode: '0755'

- name: Copy docker-compose file to server
  copy:
    src: docker-compose.yml
    dest: /opt/myapp/docker-compose.yml
    mode: '0644'

- name: Run docker-compose to deploy app
  command: docker-compose up -d
  args:
    chdir: /opt/myapp
